services:
  datasearcher:
    build:
      context: .
      dockerfile: Services/DataSearcher/DataSearcher.API/Dockerfile
    ports:
      - "8080:80"  
    depends_on: 
      - db
      
  db:
    image:
      postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "TransportData"
    ports:
      - "5432:5432"
        
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_DATABASES=1