services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  frontend:
    build:
      context: .
      dockerfile: Services/Frontend/python-docker/Dockerfile
    ports:
      - "8000:8000"
      
#  datasearcher:
#    build:
#      context: .
#      dockerfile: Services/DataSearcher/DataSearcher.API/Dockerfile
#    ports:
#      - "7001:7001"  
#    depends_on: 
#      - redis

  
#  transports:
#    build:
#      context: .
#      dockerfile: Services/Transports/Transports.API/Dockerfile
#    ports:
#      - "7002:7002"
#    depends_on:
#      - db
  
  db:
    image:
      postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "TransportData"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:  
      - "5432:5432"
        
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_DATABASES=1